package com.wesal.askhail.core.presentationEnums

object ExtraConst {
    const val EXTRA_FROM = "from"
    const val EXTRA_SUCCESS = "successRoute"
    const val EXTRA_CHAT_ID = "ChatId"
    const val EXTRA_ADVERTISER_ID = "ADVERTISER_ID"
    const val EXTRA_SECTION = "SectionModel"
    const val EXTRA_MAIN_SECTION = "mainSectionModel"
    const val EXTRA_SUB_SECTION = "subSectionModel"
    const val EXTRA_SECTION_ID = "sectionId"
    const val EXTRA_IS_BUSINESS = "isBusinessSection"
    const val EXTRA_ADVERT_ID = "advertId"
    const val EXTRA_ADVERT_PLACE = "advertHighlightPlace"
    const val EXTRA_ORDER_ID = "orderId"
    const val EXTRA_ADVERTER_ID = "adverterId"
    const val EXTRA_ADVERTER_NAME = "adverterNAme"
    const val EXTRA_PACKAGE_MODEL = "packageModel"
    const val EXTRA_ACTION_TYPE = "actionTypeForIt"
    const val EXTRA_MODEL = "TargetModel"
    const val EXTRA_BANK_MODEL = "bankModel"
    const val EXTRA_PAYMENT_URL = "paymentUrl"
    const val EXTRA_LAT = "locationLat"
    const val EXTRA_LNG = "locationLng"
    const val EXTRA_IMAGE = "image"
    const val EXTRA_ASK_ID = "AskingId"
    const val EXTRA_FIXED_PAGE_SLUG = "EXTRA_FIXED_PAGE_SLUG"
    const val EXTRA_FIXED_PAGE_TITLE = "EXTRA_FIXED_PAGE_TITLE"
    const val EXTRA_SERVICE_TYPE = "EXTRA_SERVICE_TYPE"
    const val EXTRA_IS_EDIT = "isJustForEditing"
}